### ISSUE TITLE
Problem with Installation Routine

### ISSUE THREAD

**Issue by johannesschobel** [rucken/cli#83]
Dear @EndyKaufman ,

first of all - wow, that looks like an amazing project / starter for building sophisticated web applications! Nice work!

I tried installing the project via
```sh
npm install -g @rucken/cli
rucken new test-app
cd test-app
npm install
```

but the last command (`npm install`) does not complete because of

```sh
npm ERR code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.2
```

`flatmap-stream` was removed from `npm` because of malicious code some time ago..

How can i still use the project?
All the best

**Comment by EndyKaufman** [comment]
Now I am rewriting the whole project and the structure will be a little different, maybe it will be fixed
