### ISSUE TITLE
[FAQ] Add new Application

### ISSUE THREAD

**Issue by johannesschobel** [rucken/cli#84]
Dear @EndyKaufman ,

in the `rucken/core-nestjs` project, the source for the `nestjs` application is located within `src/apps/demo`. I was just wondering, how to automatically add a new `app` to the project.

Consider, for example, the following situation:
I have a complex project that consists of several "apps", for example a dedicated app where the user may manage his user-profile and settings (lets call it `apps/user`), the main "app" (`apps/product`), a shop system (`apps/shop`) and so on..

How would you setup such an architecture?

Obviously, i can just create a new folder within `src/apps/` and go on. However, the specific "app" must also be added to the `./.nestjs.cli.json` and `./tsconfig.json` files..

What is your approach on this?
Thanks for your effort and time!

All the best

**Comment by EndyKaufman** [comment]
Now I am rewriting the whole project and the structure will be a little different, maybe it will be fixed
