### ISSUE TITLE
Translate command doesn't work with yarn

### ISSUE THREAD

**Issue by wyrd-code** [rucken/cli#92]
Hi @EndyKaufman ,

Firstly, thank you for a well structured and thought out project.

I'm using `yarn` instead of `npm` and yarn installs `@biesbjerg/ngx-translate-extract` into root `node_modules`, not within the `node_modules/@rucken/cli/node_modules/` folder, so the following path doesn't work. It doesn't make sense to have to change to `npm` because of this so it would be nice if it were compatible. 

```
const command = 'node ' + resolvePath(__dirname, '..', '..', 'node_modules/@biesbjerg/ngx-translate-extract/bin/cli.js')
```

Thank you,
Kind regards

**Comment by EndyKaufman** [comment]
New version with small fixes published, please check
